name: Notify
on:
  workflow_call:
    inputs:
      ticket:   { required: true, type: string }
      actor:    { required: true, type: string }
      phase:    { required: true, type: string }
      status:   { required: true, type: string }
      notes:    { required: false, type: string, default: "" }
      pr:       { required: false, type: string, default: "" }
      preview:  { required: false, type: string, default: "" }

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Build payloads
        run: |
          TS=$(date -Iseconds)
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"

          # ① EVENT JSON → 파일 저장 (output 사용 안 함)
          jq -n \
            --arg t "${{ inputs.ticket }}" \
            --arg a "${{ inputs.actor }}" \
            --arg p "${{ inputs.phase }}" \
            --arg s "${{ inputs.status }}" \
            --arg ts "$TS" \
            --arg pr "${{ inputs.pr }}" \
            --arg run "$RUN_URL" \
            --arg pv "${{ inputs.preview }}" \
            --arg nt "${{ inputs.notes }}" \
            '{ticket_id:$t,actor:$a,phase:$p,status:$s,ts:$ts,links:{pr:$pr,run:$run,preview:$pv},notes:$nt}' \
            > event.json

          # ② Slack 원라이너는 안전 이스케이프해서 GITHUB_ENV 로 전달
          MSG="${{ inputs.actor }} ▶ ${{ inputs.ticket }} ${{ inputs.phase }} ${{ inputs.status }} | ${{ inputs.notes }}"
          ESCAPED=$(printf '%s' "$MSG" | jq -Rsa .)
          echo "SLACK_ESCAPED=$ESCAPED" >> $GITHUB_ENV

      - name: Send EVENT JSON
        run: |
          curl -sS -X POST "${{ secrets.EVENT_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -H "x-event-secret: ${{ secrets.EVENT_SECRET }}" \
            --data-binary @event.json \
            --max-time 10 --retry 2 --retry-delay 2

      - name: Send Slack one-liner
        run: |
          curl -sS -X POST "${{ secrets.SLACK_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            --data "{\"text\":${SLACK_ESCAPED}}" \
            --max-time 10 --retry 2 --retry-delay 2

