name: Manual Ping
on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Notify (Manual)
        uses: ./.github/actions/notify
        with:
          ticket: "T-000"
          actor: "ChatGPT"
          phase: "Ops"
          status: "updated"
          notes: "Manual sync ping"
        env:
          EVENT_WEBHOOK: ${{ secrets.EVENT_WEBHOOK }}
          EVENT_SECRET:  ${{ secrets.EVENT_SECRET }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

