name: Manual Ping
on:
  workflow_dispatch:

jobs:
  ping:
    uses: yhun1542/ai-arena/.github/workflows/_notify.yml@main
    with:
      ticket: "T-000"
      actor: "ChatGPT"
      phase: "Ops"
      status: "updated"
      notes: "Manual sync ping"
    secrets: inherit

