name: Manual Ping
on: { workflow_dispatch: {} }
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/_notify.yml
        secrets: inherit
        with:
          ticket: "T-000"
          actor: "ChatGPT"
          phase: "Ops"
          status: "updated"
          notes: "Manual sync ping"

