name: Status Pulse
on:
  schedule:
    - cron: '0 * * * *'    # 매 정시 (UTC 기준)
  workflow_dispatch:

jobs:
  pulse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Summarize open PRs and recent runs
        id: sum
        run: |
          PR_COUNT=$(gh pr list --json number --jq 'length' || echo '?')
          echo "PR_COUNT=$PR_COUNT" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs: pulse
    if: always()
    uses: ./.github/workflows/_notify.yml
    secrets: inherit
    with:
      ticket:  "T-001"
      actor:   "Manus"
      phase:   "Ops"
      status:  "updated"
      notes:   "Pulse | open PRs: ${{ needs.pulse.outputs.PR_COUNT || '?' }}, latest run"

