name: Sync deploy.yml to all branches

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync deploy.yml to all branches
        run: |
          for branch in $(git branch -r | grep origin/ | grep -v origin/main | sed 's|origin/||'); do
            echo "🔄 Syncing to $branch..."
            git checkout $branch
            git checkout main -- .github/workflows/deploy.yml
            git add .github/workflows/deploy.yml
            git commit -m "chore: sync deploy.yml with main (Vercel CLI version)" || true
            git push origin $branch
          done

      - name: Switch back to main
        run: git checkout main                                                                                                                                                                                                                  - name: Summary
                                                                                                                                                                                                                                                                                                        run: |
                                                                                                                                                                                                                                                                                                                  echo "🎉 Deploy workflow synchronization completed!"
                                                                                                                                                                                                                                                                                                                            echo "📋 All branches now use the same Vercel CLI deployment configuration"
